server:
  port: 8080
  tomcat:
    # 禁用响应缓冲，确保 SSE 流式输出
    max-swallow-size: -1

spring:
  application:
    name: spring-ai-langchain4j
  main:
    allow-bean-definition-overriding: true
  # 解决SSE流式响应中文乱码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # MySQL 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring-ai?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000



  ai:
    dashscope:
      # 你的阿里云 DashScope API Key，这里配置环境变量
      api-key: ${AI_DASHSCOPE_API_KEY:sk-c287a4b8bebb48afa3bbf2249af848e4}
      chat:
        options:
          model: qwen-plus
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: qwen3.5:35b

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-c287a4b8bebb48afa3bbf2249af848e4
      model-name: qwen-plus
      log-requests: true #请求消息日志
      log-responses: true #响应消息日志
      image-gen-model:
        api-key: sk-c287a4b8bebb48afa3bbf2249af848e4
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
        model-name: wan2.2-t2i-plus
      image-vl-model:
        api-key: sk-c287a4b8bebb48afa3bbf2249af848e4
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
        model-name: qwen3-vl-plus
      image-edit-model:
        api-key: sk-c287a4b8bebb48afa3bbf2249af848e4
        base-url: https://dashscope.aliyuncs.com/api/v1
        model-name: qwen-image-edit-plus

# 日志级别
logging:
  level:
    root: INFO
    dev.langchain4j: DEBUG #日志级别
    com.alibaba.cloud.ai: DEBUG
    org.springframework.ai: DEBUG
    org:
      springframework:
          ai:
            chat:
              client:
                advisor:
                  SimpleLoggerAdvisor: DEBUG



weather:
  tools:
    url: https://cn.apihz.cn/api/tianqi/tqyb.php?id=%s&key=%s&sheng=%s&place=%s
    id:  10014930
    key: 7ee41f7ef245c9111f5869ac8d0c8b96

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.bigfly.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0